config/routes.rb
Rails.application.routes.draw do


  get 'export_csv/index', to: 'export_csv#index', as: 'export_path'

  get 'export_csv/export'

  resources :terrains
  resources :teams
  resources :matches
  get 'matches/live/:id', to: 'matches#live', as: 'live'
  get 'matches/livemanager/:id', to: 'matches#livemanager', as: 'livemanager'
  match 'matches/createevents', to: 'matches#createevents', as: 'matchevents', via: [:post]
  get 'matches/deleteevents/:id/:matchid', to: 'matches#destroymatchevents', as: 'delete_matchevents'

  get 'matches/moveup/:id', to: 'matches#moveup', as: 'moveup_match'
  get 'matches/movedown/:id', to: 'matches#movedown', as: 'movedown_match'

  get 'matches/deleteevents1users/:id/:matchid', to: 'matches#destroymatchevent1users', as: 'delete_matchevent1users'
  get 'matches/deleteevents2users/:id/:matchid', to: 'matches#destroymatchevent2users', as: 'delete_matchevent2users'
  match 'matches/createevent1users', to: 'matches#createevent1users', as: 'matchevent1users', via: [:post]
  match 'matches/createevent2users', to: 'matches#createevent2users', as: 'matchevent2users', via: [:post]
  get 'game_center/index'

  get 'game_center/live'

  get 'game_center/liveedit'

  get 'media/team'

  get 'public/team'
  get 'public/live/:id', to: 'public#live', as: 'public_live'
  get 'public/effectif2/:whom', to: 'public#effectif2'
  get 'public/player/:alias', to: 'public#player', as: 'public_player'
  get 'public/live'
  get 'public/effectif'

  get 'public/calendar'
  get 'public/currentmatch'
  get 'public/nextmatch'
  get 'public/nextmatches'

  resources :archived_infos
  resources :injuries
  resources :documents
  get 'users/getcalendardate'
  get 'users/setcalendardate'
  get 'users/getcalendartype'
  get 'users/setcalendartype'
  get 'users/changestatus/:id/:status/:wheretoredirect', to: 'users#changestatus', as: 'users_change_status'
  get 'users/oldpics/:id', to: 'users#oldpics', as: 'users_oldpics'

  get 'events/eventsource'
  get 'events/click'
  get 'events/newpartial', to: 'events#newpartial', as: 'new_events_partial'
  get 'events/showpartial/:id', to: 'events#showpartial', as: 'event_partial'
  get '/events/:id/editpartial', to: 'events#editpartial', as: 'edit_event_partial'
  resources :events
  get 'calendar/index'

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  authenticated :user do
    root to: 'users#index'

    # , as: :authenticated_root
  end

  devise_scope :user do
    root :to => 'devise/sessions#new'
  end


  # get 'event/index'



  # root 'devise/sessions#new', as: :unauthenticated_root
  # devise_scope :user do
  #   root :to => 'devise/sessions#new'
  # end
  # def after_sign_in_path_for(resource_or_scope)
  #   calendar_index_path
  # end
  #
  # def after_sign_out_path_for(resource_or_scope)
  #   calendar_index_path
  # end

  # devise_for :users

  # resources :users, only: [:index, :show]
  get 'users/index', to: 'users#index', as: 'users'
  get 'users/:id/edit', to: 'users#edit', as: 'users_edit'
  match 'users/index', to: 'users#create', as: 'createuser', via: [:post]
  resources :users, only: [:show, :update, :destroy, :new]

  get 'documents/new/:id/:doctype', to: 'documents#new', as: 'new_document_params'


end

app/models/event.rb
class Event < ApplicationRecord

  validates :begin, presence: true
  validates :end, presence: true

  has_many :subscriptions
  has_many :users, through: :subscriptions

  def getdate(value)
    if(value != nil)
      tmp = Time.at(value).strftime '%Y-%m-%dT%H:%M:%S'
      return tmp
    else
      return nil
    end
  end

  def gettime(value)
    if(value != nil)
      tmp = Time.at(value).strftime '%H:%M'
      return tmp
    else
      return nil
    end
  end

  def textstart()
    value = self.begin
    if(value != nil)
      tmp = Time.at(value).strftime '%H:%M'
      return tmp
    else
      return nil
    end

  end

  def textend()
    value = self.end
    if(value != nil)
      tmp = Time.at(value).strftime '%H:%M'
      return tmp
    else
      return nil
    end

  end

  def getnicedate(value)
    if(value != nil)
      tmp = Time.at(value).strftime '%d/%m/%Y à %H:%M'
      return tmp
    else
      return nil
    end

  end

  def getcolor()
    color = ''
    case self.eventtype
      when 1
        color = 'red'
      when 2
        color = 'grenat'
      else
        color = 'gray'
    end
    return color
  end

  def geteventtype()
    color = ''
    case self.eventtype
      when 1
        color = 'Match'
      when 2
        color = 'Entrainement'
      when 3
        color = 'Extrasportif'
      else
        color = 'gray'
    end
    return color
  end

end

app/controllers/event_controller.rb
class EventController < ApplicationController

  # skip_authorization_check :only => [:index]
  # skip_load_and_authorize_resource :only => [:index]
  # skip_authorization_check :only => [:index]
  # skip_authorization_check
  load_and_authorize_resource
  skip_before_action :authenticate_user!, only: [:index, :eventsource, :click]
  skip_authorization_check :only => [:index, :eventsource, :click]
  def index
  end

  def eventsource
    render :partial => "events/eventsource.json"
  end

  def click
    render :partial => "events/click.html"
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  # skip_before_action :authenticate_user!, only: [:index, :eventsource, :click]
  # skip_authorization_check :only => [:index, :eventsource, :click]
  authorize_resource
  before_action :set_event, only: [:show, :edit, :update, :destroy]


  def eventsource
    @events = Event.all
  end

  def click
    render :partial => "events/click.html"
  end


  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  def showpartial
    print(params)
    @event = Event.find(params['id'])
    # renderx :partial => "events/show.json"
    render :partial => "events/show.html"
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/new
  def newpartial
    @event = Event.new
    render :partial => "events/new.html"
  end

  # GET /events/1/edit
  def edit
  end

  # GET /events/1/edit
  def editpartial
    @event = Event.find(params[:id])
    render :partial => "events/edit.html"
  end

  # POST /events
  # POST /events.json
  def create
    require 'time'
    str1 = params[:event][:begin]
    params[:event][:begin] = Time.parse(str1).to_i
    str = params[:event][:end]
    if(str == '')
      params[:event][:end] = params[:event][:begin]+3600
    else
      beginday = Time.at(Time.parse(str1).to_i).strftime '%Y-%m-%d'
      params[:event][:end] =  Time.parse(beginday).to_i + Time.parse(str).to_i-Time.parse('00:00').to_i
    end
    if(params[:event][:end] < params[:event][:begin])
      params[:event][:end] = params[:event][:begin]+3600
    end

    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to calendar_index_path, notice: 'Event was successfully created.' }
        # format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    # puts params.inspect
    # print('asdasdasdasdasdas')
    # print(params[:others].delete(' ').split(/,/))

    subs = @event.subscriptions
    subs.each do |sub|
      sub.destroy
    end
    temp3 = params[:others].delete(' ').split(/,/)
    temp3.each do |numb|
      sub = Subscription.new
      sub.user_id = numb.to_i
      sub.event_id = params[:id].to_i
      sub.save
      # print(numb.to_i)
    end

    require 'time'
    str1 = params[:event][:begin]
    params[:event][:begin] = Time.parse(str1).to_i
    str = params[:event][:end]
    if(str == '')
    params[:event][:end] = params[:event][:begin]+3600
    else
      beginday = Time.at(Time.parse(str1).to_i).strftime '%Y-%m-%d'
      params[:event][:end] =  Time.parse(beginday).to_i + Time.parse(str).to_i-Time.parse('00:00').to_i
    end
    if(params[:event][:end] < params[:event][:begin])
      params[:event][:end] = params[:event][:begin]+3600
    end

    # @event.begin = '1010-10-10T10:01'
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to calendar_index_path, notice: 'Event was successfully updated.' }
        # format.json { render :show, status: :ok, location: @event }
      else

        # str = @event.begin
        # params[:event][:begin]
        # params[:event][:begin] = Time.parse(str).to_i
        # str = params[:event][:end]
        # params[:event][:end] = Time.parse(str).to_i

        # @event.begin = '1010-10-10T10:01'
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:begin, :end, :name, :description, :eventtype)
    end
end

app/helpers/event_helper.rb
module EventHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_click.html.erb
<div style="background: white; height: 200px;width: 200px;">
  test</div>

app/views/events/_edit.html.erb
<h1>Editer un évènement</h1>

<%= render 'form', event: @event %>

app/views/events/_form.html.erb
<script type="text/javascript">
var $select = $('#input-tags').selectize({
plugins: ['remove_button'],
delimiter: ',',
    valueField: 'id',

    labelField: 'name',
    searchField: 'name',
persist: false,
    options: [
        <%
          players = User.where(canrole: 'premiere')
          players.each do |player|
        %>
        {id: ' <%= player.id %>', name: '<%= player.getname() %>'},
        <% end %>


    ],
create: function(input) {
return {
value: input,
text: input
}
}
});



var selectize = $select[0].selectize;
//selectize.setValue(selectize.search("4").items[0].id);
//alert(selectize.search("5").items[0].id)
var selected_items = [];
<%

@event.subscriptions.each do |sub|
  print('selected_items.push(selectize.search("'+sub.user.getname().to_s+'").items[0].id);')
  %>
<%= raw 'selected_items.push(selectize.search("'+sub.user.getname().to_s+'").items[0].id);' %>

<%
 end

%>
//selected_items.push(selectize.search("5").items[0].id);
//selected_items.push(selectize.search("4").items[0].id);

selectize.setValue(selected_items);


</script>

<%= form_for(event) do |f| %>
  <%

    # event.begin = '09.09.2000 09:09'

    if event.errors.any?

  %>
    <div id="error_explanation">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>





  <div class="form-group">
    <%= f.label :begin , 'Début' %>
    <%=
      str = event.getdate(event.begin)
      f.datetime_local_field :begin, value: str, class:'form-control'
    %>
  </div>

  <div class="form-group">
    <%= f.label :end , 'Fin' %>
    <%=
      str = event.gettime(event.end)
    f.time_field :end, value: str, class:'form-control'
    %>
  </div>

  <div class="form-group">
    <%= f.label :name , 'Titre' %>
    <%= f.text_field :name, class:'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :description , 'Description' %>
    <%= f.text_field :description, class:'form-control' %>
  </div>



  <div class="form-group">
    <%= f.label :eventtype, "Type d'évènement" %>
    <%=
      # f.text_field :eventtype
    %>
    <%= f.select :eventtype, options_for_select([["Match", "1"], ["Entrainement", "2"], ["Extra-Sportif", "3"]], event.eventtype), class:'form-control' %>
  </div>

    <div class="form-group">
    <label for="event_others">Membres</label>
    <input class="form-control" id="input-tags" name="others" type="text" >
    </div>
    <%
      stringofmails = '';
      @event.subscriptions.each do |sub|
        stringofmails = stringofmails+sub.user.email+';'
      end
    %>
    <%=
      if(!@event.name.blank?)
      raw '<a class="btn btn-primary" href="mailto:'+stringofmails+'?subject=Evènement: '+@event.name+'&body=Voici un email">Envoyer un email</a>'
end
    %>
<br><br>

  <div class="actions">
    <%= f.submit 'Enregistrer', class:'btn' %>
  </div>
<% end %>

app/views/events/_new.html.erb
<h1>New Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Back', events_path %>

app/views/events/_show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Début:</strong>
  <%= @event.getnicedate(@event.begin) %>
</p>

<p>
  <strong>Fin:</strong>
  <%= @event.getnicedate(@event.end) %>
</p>

<p>
  <strong>Titre:</strong>
  <%= @event.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @event.description %>
</p>

<p>
  <strong>Type d'évènement:</strong>
  <span style="color: <%= @event.getcolor() %>;"><%= @event.geteventtype() %></span>
</p>

<p>
  <strong>Membres:</strong>
  <%
  @event.subscriptions.each do |sub|
  %>
      <%= link_to ('<u>'+sub.user.getname()+'</u>').html_safe, user_path(sub.user.id), class: 'blacklink' %>
  <%
    end
  %>
</p>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form', event: @event %>

app/views/events/index.html.erb
<% if notice %>
    <div class="alert alert-success" role="alert">
      <p id="notice"><%= notice %></p>
    </div>
<% end %>

<div class="container">

<table id="eventsindex" class="table table-striped	">
  <thead>
    <tr>
      <th>Début</th>
      <th>Fin</th>
      <th>Titre</th>
      <th>Description</th>
      <th>Type</th>
      <% if current_user.canrole == 'admin' %>
      <th></th>
      <% end %>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
      <tr class='clickable-row' data-href="<%=event_path(event)%>">
        <td><%= event.getnicedate(event.begin) %></td>
        <td><%= event.getnicedate(event.end) %></td>
        <td><%= event.name %></td>
        <td><%= event.description %></td>
        <td>
          <% if event.eventtype ==1%>
              <span style="display: none;">1</span>
              Match
          <% end %>
          <% if event.eventtype == 2%>
              <span style="display: none;">2</span>
              Entrainement
          <% end %>
        </td>
        <% if current_user.canrole == 'admin' %>
            <td style="overflow: hidden; white-space: nowrap;">
              <% if current_user.canrole == 'admin' %>
                  <%= link_to '<i class="fa fa-search" aria-hidden="true"></i>'.html_safe, event, class: 'btn btn-success btn-user'%>
                  <%= link_to '<i class="fa fa-pencil" aria-hidden="true"></i>'.html_safe, edit_event_path(event), class: 'btn btn-warning btn-user' %>
                  <%= link_to '<i class="fa fa-times" aria-hidden="true"></i>'.html_safe, event, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-user' %>
              <% end %>
            </td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Event', new_event_path, class: 'btn btn-primary' %>

</div>

app/views/events/new.html.erb
<h1>New Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<% if notice %>
    <div class="alert alert-success" role="alert">
      <p id="notice"><%= notice %></p>
    </div>
<% end %>

<div class="row">

  <div class="col-5">
    <div class="col-12">
      <div class="thumbnail">
        <div class="caption">
          <h3><%= @event.name %></h3>
          <ul class="list-group">
            <li class="list-group-item" style="font-weight: bold">
              <% if @event.eventtype ==1%>
                  Match
              <% end %>
              <% if @event.eventtype == 2%>
                  Entrainement
              <% end %>
            </li>
            <li class="list-group-item"><%= @event.getnicedate(@event.begin) %></li>
            <li class="list-group-item"><%= @event.getnicedate(@event.end) %></li>
          </ul>
          <br>
          <%= link_to 'Edit', edit_event_path(@event), class: 'btn btn-primary' %> |
          <%= link_to 'Back', events_path, class: 'btn btn-primary' %>
        </div>
      </div>
    </div>
  </div>

  <div class="col-7 thumbnail">
    <p>
      <strong>Description:</strong>
      <%= @event.description %>

    </p>

  </div>

</div> <!-- /.row -->