config/routes.rb
Rails.application.routes.draw do


  get 'export_csv/index', to: 'export_csv#index', as: 'export_path'

  get 'export_csv/export'

  resources :terrains
  resources :teams
  resources :matches
  get 'matches/live/:id', to: 'matches#live', as: 'live'
  get 'matches/livemanager/:id', to: 'matches#livemanager', as: 'livemanager'
  match 'matches/createevents', to: 'matches#createevents', as: 'matchevents', via: [:post]
  get 'matches/deleteevents/:id/:matchid', to: 'matches#destroymatchevents', as: 'delete_matchevents'

  get 'matches/moveup/:id', to: 'matches#moveup', as: 'moveup_match'
  get 'matches/movedown/:id', to: 'matches#movedown', as: 'movedown_match'

  get 'matches/deleteevents1users/:id/:matchid', to: 'matches#destroymatchevent1users', as: 'delete_matchevent1users'
  get 'matches/deleteevents2users/:id/:matchid', to: 'matches#destroymatchevent2users', as: 'delete_matchevent2users'
  match 'matches/createevent1users', to: 'matches#createevent1users', as: 'matchevent1users', via: [:post]
  match 'matches/createevent2users', to: 'matches#createevent2users', as: 'matchevent2users', via: [:post]
  get 'game_center/index'

  get 'game_center/live'

  get 'game_center/liveedit'

  get 'media/team'

  get 'public/team'
  get 'public/live/:id', to: 'public#live', as: 'public_live'
  get 'public/effectif2/:whom', to: 'public#effectif2'
  get 'public/player/:alias', to: 'public#player', as: 'public_player'
  get 'public/live'
  get 'public/effectif'

  get 'public/calendar'
  get 'public/currentmatch'
  get 'public/nextmatch'
  get 'public/nextmatches'

  resources :archived_infos
  resources :injuries
  resources :documents
  get 'users/getcalendardate'
  get 'users/setcalendardate'
  get 'users/getcalendartype'
  get 'users/setcalendartype'
  get 'users/changestatus/:id/:status/:wheretoredirect', to: 'users#changestatus', as: 'users_change_status'
  get 'users/oldpics/:id', to: 'users#oldpics', as: 'users_oldpics'

  get 'events/eventsource'
  get 'events/click'
  get 'events/newpartial', to: 'events#newpartial', as: 'new_events_partial'
  get 'events/showpartial/:id', to: 'events#showpartial', as: 'event_partial'
  get '/events/:id/editpartial', to: 'events#editpartial', as: 'edit_event_partial'
  resources :events
  get 'calendar/index'

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  authenticated :user do
    root to: 'users#index'

    # , as: :authenticated_root
  end

  devise_scope :user do
    root :to => 'devise/sessions#new'
  end


  # get 'event/index'



  # root 'devise/sessions#new', as: :unauthenticated_root
  # devise_scope :user do
  #   root :to => 'devise/sessions#new'
  # end
  # def after_sign_in_path_for(resource_or_scope)
  #   calendar_index_path
  # end
  #
  # def after_sign_out_path_for(resource_or_scope)
  #   calendar_index_path
  # end

  # devise_for :users

  # resources :users, only: [:index, :show]
  get 'users/index', to: 'users#index', as: 'users'
  get 'users/:id/edit', to: 'users#edit', as: 'users_edit'
  match 'users/index', to: 'users#create', as: 'createuser', via: [:post]
  resources :users, only: [:show, :update, :destroy, :new]

  get 'documents/new/:id/:doctype', to: 'documents#new', as: 'new_document_params'


end

app/models/archived_info.rb
class ArchivedInfo < ApplicationRecord
  belongs_to :user
end

app/controllers/archived_infos_controller.rb
class ArchivedInfosController < ApplicationController
  before_action :set_archived_info, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource

  # GET /archived_infos
  # GET /archived_infos.json
  def index
    @archived_infos = ArchivedInfo.all
  end

  # GET /archived_infos/1
  # GET /archived_infos/1.json
  def show
  end

  # GET /archived_infos/new
  def new
    @archived_info = ArchivedInfo.new
  end

  # GET /archived_infos/1/edit
  def edit
  end

  # POST /archived_infos
  # POST /archived_infos.json
  def create
    @archived_info = ArchivedInfo.new(archived_info_params)

    respond_to do |format|
      if @archived_info.save
        format.html { redirect_to @archived_info, notice: 'Archived info was successfully created.' }
        format.json { render :show, status: :created, location: @archived_info }
      else
        format.html { render :new }
        format.json { render json: @archived_info.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /archived_infos/1
  # PATCH/PUT /archived_infos/1.json
  def update
    respond_to do |format|
      if @archived_info.update(archived_info_params)
        format.html { redirect_to @archived_info, notice: 'Archived info was successfully updated.' }
        format.json { render :show, status: :ok, location: @archived_info }
      else
        format.html { render :edit }
        format.json { render json: @archived_info.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /archived_infos/1
  # DELETE /archived_infos/1.json
  def destroy
    temppath = @archived_info.user_id
    @archived_info.destroy
    respond_to do |format|
      format.html { redirect_to user_path(temppath), notice: 'Archived info was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_archived_info
      @archived_info = ArchivedInfo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def archived_info_params
      params.fetch(:archived_info, {})
    end
end

app/helpers/archived_infos_helper.rb
module ArchivedInfosHelper
end

app/views/archived_infos/_form.html.erb
<%= form_for(archived_info) do |f| %>
  <% if archived_info.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(archived_info.errors.count, "error") %> prohibited this archived_info from being saved:</h2>

      <ul>
      <% archived_info.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/archived_infos/edit.html.erb
<h1>Editing Archived Info</h1>

<%= render 'form', archived_info: @archived_info %>

<%= link_to 'Show', @archived_info %> |
<%= link_to 'Back', archived_infos_path %>

app/views/archived_infos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Archived Infos</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @archived_infos.each do |archived_info| %>
      <tr>
        <td><%= link_to 'Show', archived_info %></td>
        <td><%= link_to 'Edit', edit_archived_info_path(archived_info) %></td>
        <td><%= link_to 'Destroy', archived_info, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Archived Info', new_archived_info_path %>

app/views/archived_infos/new.html.erb
<h1>New Archived Info</h1>

<%= render 'form', archived_info: @archived_info %>

<%= link_to 'Back', archived_infos_path %>

app/views/archived_infos/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_archived_info_path(@archived_info) %> |
<%= link_to 'Back', archived_infos_path %>