config/routes.rb
Rails.application.routes.draw do


  get 'export_csv/index', to: 'export_csv#index', as: 'export_path'

  get 'export_csv/export'

  resources :terrains
  resources :teams
  resources :matches
  get 'matches/live/:id', to: 'matches#live', as: 'live'
  get 'matches/livemanager/:id', to: 'matches#livemanager', as: 'livemanager'
  match 'matches/createevents', to: 'matches#createevents', as: 'matchevents', via: [:post]
  get 'matches/deleteevents/:id/:matchid', to: 'matches#destroymatchevents', as: 'delete_matchevents'

  get 'matches/moveup/:id', to: 'matches#moveup', as: 'moveup_match'
  get 'matches/movedown/:id', to: 'matches#movedown', as: 'movedown_match'

  get 'matches/deleteevents1users/:id/:matchid', to: 'matches#destroymatchevent1users', as: 'delete_matchevent1users'
  get 'matches/deleteevents2users/:id/:matchid', to: 'matches#destroymatchevent2users', as: 'delete_matchevent2users'
  match 'matches/createevent1users', to: 'matches#createevent1users', as: 'matchevent1users', via: [:post]
  match 'matches/createevent2users', to: 'matches#createevent2users', as: 'matchevent2users', via: [:post]
  get 'game_center/index'

  get 'game_center/live'

  get 'game_center/liveedit'

  get 'media/team'

  get 'public/team'
  get 'public/live/:id', to: 'public#live', as: 'public_live'
  get 'public/effectif2/:whom', to: 'public#effectif2'
  get 'public/player/:alias', to: 'public#player', as: 'public_player'
  get 'public/live'
  get 'public/effectif'

  get 'public/calendar'
  get 'public/currentmatch'
  get 'public/nextmatch'
  get 'public/nextmatches'

  resources :archived_infos
  resources :injuries
  resources :documents
  get 'users/getcalendardate'
  get 'users/setcalendardate'
  get 'users/getcalendartype'
  get 'users/setcalendartype'
  get 'users/changestatus/:id/:status/:wheretoredirect', to: 'users#changestatus', as: 'users_change_status'
  get 'users/oldpics/:id', to: 'users#oldpics', as: 'users_oldpics'

  get 'events/eventsource'
  get 'events/click'
  get 'events/newpartial', to: 'events#newpartial', as: 'new_events_partial'
  get 'events/showpartial/:id', to: 'events#showpartial', as: 'event_partial'
  get '/events/:id/editpartial', to: 'events#editpartial', as: 'edit_event_partial'
  resources :events
  get 'calendar/index'

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  authenticated :user do
    root to: 'users#index'

    # , as: :authenticated_root
  end

  devise_scope :user do
    root :to => 'devise/sessions#new'
  end


  # get 'event/index'



  # root 'devise/sessions#new', as: :unauthenticated_root
  # devise_scope :user do
  #   root :to => 'devise/sessions#new'
  # end
  # def after_sign_in_path_for(resource_or_scope)
  #   calendar_index_path
  # end
  #
  # def after_sign_out_path_for(resource_or_scope)
  #   calendar_index_path
  # end

  # devise_for :users

  # resources :users, only: [:index, :show]
  get 'users/index', to: 'users#index', as: 'users'
  get 'users/:id/edit', to: 'users#edit', as: 'users_edit'
  match 'users/index', to: 'users#create', as: 'createuser', via: [:post]
  resources :users, only: [:show, :update, :destroy, :new]

  get 'documents/new/:id/:doctype', to: 'documents#new', as: 'new_document_params'


end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController
  before_action :set_match, only: [:show, :edit, :update, :destroy]
  authorize_resource
  # GET /matches
  # GET /matches.json
  def index
    if (params[:format] == 'old')
      @matches = Match.all.select { |u| u.when+240*60 < Time.now.to_i }
      @matches = @matches.sort_by &:when
      @matches = @matches.reverse
    else
      @matches = Match.all.select { |u| u.when+240*60 > Time.now.to_i }
      @matches = @matches.sort_by &:when

    end
  end

  # GET /matches/1
  # GET /matches/1.json
  def show

  end

  def livemanager
    set_match
    @simple = Matchevent.new
    @one = Matchevent1user.new
    @two = Matchevent2user.new
  end

  def createevents
    @simple = Matchevent.new(matchevent_params)

    respond_to do |format|
      if @simple.save

        @link = Matcheventlink.new
        @link.imageable_type = @simple.class.name
        @link.imageable_id = @simple.id
        @link.match_id = @simple.match_id
        @link.temps = @simple.temps
        @link.theorder = -1
        @link.save
        @link.theorder = @link.getorder()

        require 'open-uri'
        open("http://www.servettefc.ch/cron2.php")
        open("http://www.servettefc.ch/cron3.php?id="+@simple.match_id.to_s)

        format.html { redirect_to livemanager_path(@simple.match_id), notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @match }
      else
        format.html { render :new }
        format.json { render json: @match.errors, status: :unprocessable_entity }
      end
    end
  end

  def createevent1users
    @simple = Matchevent1user.new(matchevent1user_params)

    respond_to do |format|
      if @simple.save

        @link = Matcheventlink.new
        @link.imageable_type = @simple.class.name
        @link.imageable_id = @simple.id
        @link.match_id = @simple.match_id
        @link.temps = @simple.temps
        @link.theorder = -1
        @link.save
        @link.theorder = @link.getorder()

        require 'open-uri'
        open("http://www.servettefc.ch/cron2.php")
        open("http://www.servettefc.ch/cron3.php?id="+@simple.match_id.to_s)

        format.html { redirect_to livemanager_path(@simple.match_id), notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @match }
      else
        format.html { render :new }
        format.json { render json: @match.errors, status: :unprocessable_entity }
      end
    end
  end

  def createevent2users
    @simple = Matchevent2user.new(matchevent2user_params)

    respond_to do |format|
      if @simple.save

        @link = Matcheventlink.new
        @link.imageable_type = @simple.class.name
        @link.imageable_id = @simple.id
        @link.match_id = @simple.match_id
        @link.temps = @simple.temps
        @link.theorder = -1
        @link.save
        @link.theorder = @link.getorder()

        require 'open-uri'
        open("http://www.servettefc.ch/cron2.php")
        open("http://www.servettefc.ch/cron3.php?id="+@simple.match_id.to_s)

        format.html { redirect_to livemanager_path(@simple.match_id), notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @match }
      else
        format.html { render :new }
        format.json { render json: @match.errors, status: :unprocessable_entity }
      end
    end
  end


  def live

    set_match
    @matches = Match.all
    @matches.each do |m|
      m.live = false
      m.save
    end
    if (@match.live)
      @match.live = false
    else
      @match.live = true
    end
    @match.save

    require 'open-uri'
    open("http://www.servettefc.ch/cron2.php")
    open("http://www.servettefc.ch/cron3.php?id="+@match.id.to_s)

    redirect_to matches_path

  end

  # GET /matches/new
  def new
    @match = Match.new
  end

  # GET /matches/1/edit
  def edit
  end

  # POST /matches
  # POST /matches.json
  def create
    require 'time'
    str1 = params[:match][:when]
    params[:match][:when] = Time.parse(str1).to_i

    @match = Match.new(match_params)

    respond_to do |format|
      if @match.save
        format.html { redirect_to edit_match_path(@match), notice: 'Match was successfully created.' }
        format.json { render :show, status: :created, location: @match }
      else
        format.html { render :new }
        format.json { render json: @match.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /matches/1
  # PATCH/PUT /matches/1.json
  def update

    links = @match.matchlinks
    links.each do |l|
      l.destroy
    end
    puts params.inspect
    temp = params[:hometitulaires].delete(' ').split(/,/)
    temp.each do |t|
      l = Matchlink.new
      l.user_id = t.to_i
      l.match_id = @match.id.to_i
      l.thetype = 'titulaires'
      l.save
    end
    temp = params[:homeremplacents].delete(' ').split(/,/)
    temp.each do |t|
      l = Matchlink.new
      l.user_id = t.to_i
      l.match_id = @match.id.to_i
      l.thetype = 'remplacents'
      l.save
    end
    temp = params[:homeabsents].delete(' ').split(/,/)
    temp.each do |t|
      l = Matchlink.new
      l.user_id = t.to_i
      l.match_id = @match.id.to_i
      l.thetype = 'absents'
      l.save
    end

    require 'time'
    str1 = params[:match][:when]
    params[:match][:when] = Time.parse(str1).to_i

    respond_to do |format|
      if @match.update(match_params)
        format.html { redirect_to matches_path, notice: 'Match was successfully updated.' }
        format.json { render :show, status: :ok, location: @match }
      else
        format.html { render :edit }
        format.json { render json: @match.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /matches/1
  # DELETE /matches/1.json
  def destroy
    @match.destroy
    respond_to do |format|
      format.html { redirect_to matches_url, notice: 'Match was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def destroymatchevents
    Matchevent.find(params[:id]).matcheventlink.removefromorder()
    Matchevent.find(params[:id]).destroy

    require 'open-uri'
    open("http://www.servettefc.ch/cron2.php")
    open("http://www.servettefc.ch/cron3.php?id="+params[:matchid].to_s)

    match = Match.find(params[:matchid])
    respond_to do |format|
      format.html { redirect_to livemanager_path(match.id), notice: 'Match was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def destroymatchevent1users
    Matchevent1user.find(params[:id]).matcheventlink.removefromorder()
    Matchevent1user.find(params[:id]).destroy

    require 'open-uri'
    open("http://www.servettefc.ch/cron2.php")
    open("http://www.servettefc.ch/cron3.php?id="+params[:matchid].to_s)

    match = Match.find(params[:matchid])
    respond_to do |format|
      format.html { redirect_to livemanager_path(match.id), notice: 'Match was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  def destroymatchevent2users
    Matchevent2user.find(params[:id]).matcheventlink.removefromorder()
    Matchevent2user.find(params[:id]).destroy

    require 'open-uri'
    open("http://www.servettefc.ch/cron2.php")
    open("http://www.servettefc.ch/cron3.php?id="+params[:matchid].to_s)

    match = Match.find(params[:matchid])
    respond_to do |format|
      format.html { redirect_to livemanager_path(match.id), notice: 'Match was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def moveup
    Matcheventlink.find(params[:id]).moveup()
    require 'open-uri'
    open("http://www.servettefc.ch/cron2.php")
    open("http://www.servettefc.ch/cron3.php?id="+params[:matchid].to_s)

    match = Matcheventlink.find(params[:id]).match
    respond_to do |format|
      format.html { redirect_to livemanager_path(match.id), notice: 'Event was successfully changed.' }
      format.json { head :no_content }
    end
  end

  def movedown
    Matcheventlink.find(params[:id]).movedown()
    require 'open-uri'
    open("http://www.servettefc.ch/cron2.php")
    open("http://www.servettefc.ch/cron3.php?id="+params[:matchid].to_s)

    match = Matcheventlink.find(params[:id]).match
    respond_to do |format|
      format.html { redirect_to livemanager_path(match.id), notice: 'Event was successfully changed.' }
      format.json { head :no_content }
    end
  end


  private
  # Use callbacks to share common setup or constraints between actions.
  def set_match
    @match = Match.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def match_params
    params.require(:match).permit(:compterendu,:photos,:videos,:home,:when, :équipe, :adversaire_id, :saison, :scoreSfc, :scoreAdv, :spectateurs, :competition, :terrain_id, :hometitulaires, :homeremplacents, :homeabsents, :homeentrainer, :awaytitulaires, :awayremplacants, :awayabsents, :awayentrainer)
  end
  def matchevent_params
    params.require(:matchevent).permit(:match_id, :commentaire,:player, :temps, :thetype)
  end

  def matchevent1user_params
    params.require(:matchevent1user).permit(:match_id, :user_id, :commentaire, :temps, :thetype)
  end

  def matchevent2user_params
    params.require(:matchevent2user).permit(:match_id, :user_one_id, :user_two_id, :commentaire, :temps, :thetype)
  end

end

app/helpers/matches_helper.rb
module MatchesHelper
end

app/views/matches/_form.html.erb
<%= link_to 'Retour aux matchs', matches_path, class: 'btn btn-primary' %><br><br>
<%= form_for(match) do |f| %>
    <% if match.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(match.errors.count, "error") %> prohibited this match from being saved:</h2>

          <ul>
            <% match.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>



    <div class="row">
      <div class="col-4">

        <div class="form-group">
          <%= f.label :équipe, "Equipe" %>
          <%=
            f.select :équipe, options_for_select([["Servette FC", "Servette FC"]], match.équipe)
          %>
          <%=
            # f.select :équipe, options_for_select([["Premiere", "Premiere"], ["M21", "M21"], ["M18", "M18"], ["M16", "M16"], ["M15", "M15"], ["FE14", "FE14"], ["FE13", "FE13"], ["FE12", "FE12"], ["FE11", "FE11"], ["FC10", "FC10"], ["FC9", "FC9"], ["FC8", "FC8"], ["FC7", "FC7"]], match.équipe)
          %>
        </div>

        <div class="form-group">
          <%= f.label :adversaire_id, "Adversaire" %>
          <%
            teams = Team.order('name').all
            mains = []
            teams.each do |team|
              if (team.category == 0)
                mains.push([team.name, team.id])
              end
            end
            teams.each do |team|
              if (team.category == 1)
                mains.push([team.name, team.id])
              end
            end
          %>
          <%= f.select :adversaire_id, options_for_select(mains, match.adversaire_id) %>        </div>

        <div class="form-group">
          <%= f.label :saison, "Saison" %>
          <%= f.select :saison, options_for_select([["2017/2018", "2017/2018"], ["2016/2017", "2016/2017"]], match.saison) %>
        </div>

        <div class="form-group">
          <%= f.label :when, 'Date' %>
          <%=
            str = match.getdate(match.when)
            f.datetime_local_field :when, value: str, class: 'form-control'
          %>
        </div>


        <!--<div class="form-group">-->
        <!--<%= f.label :scoreSfc, "Score SFC" %>-->
        <!--<%= f.text_field :scoreSfc, class: 'form-control' %>-->
        <!--</div>-->
        <!--<div class="form-group">-->
        <!--<%= f.label :scoreAdv, "Score adversaire" %>-->
        <!--<%= f.text_field :scoreAdv, class: 'form-control' %>-->
        <!--</div>-->
        <div class="form-group">
          <%= f.label :spectateurs, "Spectateur" %>
          <%= f.text_field :spectateurs, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :competition, "Compétition" %>
          <%= f.select :competition, options_for_select([["Brack.ch Challenge League", "Brack.ch Challenge League"], ["Amical", "Amical"], ["Coupe Suisse", "Coupe Suisse"]], match.competition) %>
        </div>

        <div class="form-group">
          <%= f.label :terrain_id, "Terrain" %>
          <%
            teams = Terrain.order('name').all
            mains = []
            teams.each do |team|
              if (team.category == 0)
                mains.push([team.name, team.id])
              end
            end
            teams.each do |team|
              if (team.category == 1)
                mains.push([team.name, team.id])
              end
            end
          %>
          <%= f.select :terrain_id, options_for_select(mains, match.terrain_id) %>        </div>

        <div class="form-group">
          <%= f.label :home, "Domicile" %>
          <%= f.check_box :home, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :photos, "URL photos" %>
          <%= f.text_field :photos, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :videos, "URL videos" %>
          <%= f.text_field :videos, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :compterendu, "Compte-rendu" %>
          <%= f.text_field :compterendu, class: 'form-control' %>
        </div>
      </div>

      <div class="col-4">
        <div class="form-group">
          <label for="match_hometitulaires">Titulaires home team</label>
          <input class="form-control" id="input-tags" name="hometitulaires" type="text">
        </div>
        <div class="form-group">
          <label for="match_homeremplacents">Remplacents home team</label>
          <input class="form-control" id="input-tags2" name="homeremplacents" type="text">
        </div>
        <div class="form-group">
          <label for="match_homeabsents">Absents home team</label>
          <input class="form-control" id="input-tags3" name="homeabsents" type="text">
        </div>

        <div class="form-group">
          <%= f.label :homeentrainer, "Entraineur home team" %>
          <%= f.text_field :homeentrainer, class: 'form-control' %>
        </div>
      </div>

      <div class="col-4">
        <div class="form-group">
          <%= f.label :awaytitulaires, "Titulaires away team" %>
          <%= f.text_area :awaytitulaires, class: 'form-control' %>
        </div>

        <div class="form-group">
          <%= f.label :awayremplacants, "Remplacants away team" %>
          <%= f.text_area :awayremplacants, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :awayabsents, "Absents away team" %>
          <%= f.text_area :awayabsents, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :awayentrainer, "Entraineur away team" %>
          <%= f.text_field :awayentrainer, class: 'form-control' %>
        </div>

        <div class="actions">
          <%= f.submit %>
        </div>
      </div>
    </div>
<% end %>


<script type="text/javascript">

    $(document).ready(function () {
        var $select = $('#input-tags').selectize({
            plugins: ['remove_button'],
            delimiter: ',',
            valueField: 'id',

            labelField: 'name',
            searchField: 'name',
            persist: false,
            options: [
                <%
                  players = User.getplayers()
                  players.each do |player|
                %>
                {id: ' <%= player.id %>', name: '<%= player.getname() %>'},
                <% end %>


            ],
            create: function (input) {
                return {
                    value: input,
                    text: input
                }
            }
        });


        var selectize = $select[0].selectize;
        var selected_items = [];
        <%

        match.matchlinks.each do |link|
          %>
        <% if link.thetype == 'titulaires' %>
        <%= raw 'selected_items.push(selectize.search("'+link.user.getname().to_s+'").items[0].id);' %>
        <% end %>
        <%
         end

        %>
        selectize.setValue(selected_items);
    });

</script>
<script type="text/javascript">

    $(document).ready(function () {
        var $select = $('#input-tags2').selectize({
            plugins: ['remove_button'],
            delimiter: ',',
            valueField: 'id',

            labelField: 'name',
            searchField: 'name',
            persist: false,
            options: [
                <%
                  players =  User.getplayers()
                  players.each do |player|
                %>
                {id: ' <%= player.id %>', name: '<%= player.getname() %>'},
                <% end %>


            ],
            create: function (input) {
                return {
                    value: input,
                    text: input
                }
            }
        });


        var selectize = $select[0].selectize;
        var selected_items = [];
        <%

        match.matchlinks.each do |link|
          %>
        <% if link.thetype == 'remplacents' %>
        <%= raw 'selected_items.push(selectize.search("'+link.user.getname().to_s+'").items[0].id);' %>
        <% end %>
        <%
         end

        %>
        selectize.setValue(selected_items);
    });

</script>

<script type="text/javascript">

    $(document).ready(function () {
        var $select = $('#input-tags3').selectize({
            plugins: ['remove_button'],
            delimiter: ',',
            valueField: 'id',

            labelField: 'name',
            searchField: 'name',
            persist: false,
            options: [
                <%
                  players =  User.getplayers()
                  players.each do |player|
                %>
                {id: ' <%= player.id %>', name: '<%= player.getname() %>'},
                <% end %>


            ],
            create: function (input) {
                return {
                    value: input,
                    text: input
                }
            }
        });


        var selectize = $select[0].selectize;
        var selected_items = [];
        <%

        match.matchlinks.each do |link|
          %>
        <% if link.thetype == 'absents' %>
        <%= raw 'selected_items.push(selectize.search("'+link.user.getname().to_s+'").items[0].id);' %>
        <% end %>
        <%
         end

        %>
        selectize.setValue(selected_items);
    });

</script>

app/views/matches/_form2.html.erb
<%= link_to 'Retour aux matchs', matches_path , class: 'btn btn-primary'%><br><br>

<%= form_for(match) do |f| %>
    <% if match.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(match.errors.count, "error") %> prohibited this match from being saved:</h2>

          <ul>
            <% match.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>



    <div class="row">
      <div class="col-3">

        <div class="form-group">
          <%= f.label :équipe, "Equipe" %>
          <%=
            f.select :équipe, options_for_select([["Servette FC", "Servette FC"]], match.équipe)
          %>
          <%=
            # f.select :équipe, options_for_select([["Premiere", "Premiere"], ["M21", "M21"], ["M18", "M18"], ["M16", "M16"], ["M15", "M15"], ["FE14", "FE14"], ["FE13", "FE13"], ["FE12", "FE12"], ["FE11", "FE11"], ["FC10", "FC10"], ["FC9", "FC9"], ["FC8", "FC8"], ["FC7", "FC7"]], match.équipe)
          %>        </div>

        <div class="form-group">
          <%= f.label :adversaire_id, "Adversaire" %>
          <%
            teams = Team.order('name').all
            mains = []
            teams.each do |team|
              if (team.category == 0)
                mains.push([team.name, team.id])
              end
            end
            teams.each do |team|
              if (team.category == 1)
                mains.push([team.name, team.id])
              end
            end
            %>
            <%= f.select :adversaire_id, options_for_select(mains, match.adversaire_id) %>
        </div>

        <div class="form-group">
          <%= f.label :saison, "Saison" %>
          <%= f.select :saison, options_for_select([["2017/2018", "2017/2018"],["2016/2017", "2016/2017"]], match.saison) %>
        </div>

        <div class="form-group">
          <%= f.label :when, 'Date' %>
          <%=
            str = match.getdate(match.when)
            f.datetime_local_field :when, value: str, class: 'form-control'
          %>
        </div>
        <div class="form-group">
          <%= f.label :home, "Domicile" %>
          <%= f.check_box :home, class: 'form-control' %>
        </div>


        <div class="form-group">
          <%= f.label :competition, "Compétition" %>
          <%= f.select :competition, options_for_select([["Brack.ch Challenge League", "Brack.ch Challenge League"],["Amical", "Amical"],["Coupe Suisse", "Coupe Suisse"]], match.competition) %>
        </div>

        <div class="form-group">
          <%= f.label :terrain_id, "Terrain" %>
          <%
            teams = Terrain.order('name').all
            mains = []
            teams.each do |team|
              if (team.category == 0)
                mains.push([team.name, team.id])
              end
            end
            teams.each do |team|
              if (team.category == 1)
                mains.push([team.name, team.id])
              end
            end
          %>
          <%= f.select :terrain_id, options_for_select(mains, match.terrain_id) %>
        </div>


        <div class="actions">
          <%= f.submit %>
        </div>
      </div>
    </div>
<% end %>

app/views/matches/edit.html.erb
<h1>Editing Match</h1>

<%= render 'form', match: @match %>

app/views/matches/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Matches</h1>
<%
  @temps = Match.all
  @temps.each do |m|
    if m.live
%>
        <%= link_to 'GESTION DU LIVE', livemanager_path(m.id), class: 'btn btn-success' %><br><br>
    <%
      end
      end
    %>


<%= link_to 'Nouveau Match', new_match_path, class: 'btn btn-primary' %>
<% if (params[:format] == 'old') %>
    <%= link_to 'Match à venir', matches_path, class: 'btn btn-primary' %>
<% else %>
    <%= link_to 'Anciens Match', matches_path('old'), class: 'btn btn-primary' %>
<% end %>
<%= link_to 'Gestion des équipes', teams_path, class: 'btn btn-primary' %>
<%= link_to 'Gestion des terrains', terrains_path, class: 'btn btn-primary' %>

<table class="table table-striped	">
  <thead>
  <tr>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @matches.each do |match| %>
      <tr>
        <td><%= Time.at(match.when).strftime '%d/%m/%Y à %H:%M' %></td>
        <td><%= match.équipe %> vs. <%= match.adversaire.name %></td>
        <td><%= match.terrain.name %></td>
        <td><%= link_to 'Visualiser', match, class: 'btn btn-primary' %></td>
        <td><%= link_to 'Editer', edit_match_path(match), class: 'btn btn-primary' %></td>
        <td><%= link_to 'Supprimer', match, method: :delete, data: {confirm: 'Are you sure?'}, class: 'btn btn-primary' %></td>
        <td>
          <% if (!match.live) %>
              <% if !(params[:format] == 'old') %>
                  <%= link_to 'Go live', live_path(match.id), data: {confirm: 'Are you sure?'}, class: 'btn btn-primary' %>
              <% else %>
                  <%= link_to 'Editer Evènements',  livemanager_path(match.id), class: 'btn btn-primary' %>
              <% end %>
          <% else %>
              <%= link_to 'Fin du live', live_path(match.id), data: {confirm: 'Are you sure?'}, class: 'btn btn-success' %>
          <% end %>
        </td>
      </tr>
  <% end %>
  </tbody>
</table>

<br>

app/views/matches/new.html.erb
<h1>New Match</h1>

<%= render 'form2', match: @match %>

<%= link_to 'Back', matches_path %>